# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
  batch: true
  branches:
    include:
    - master

pr: none

pool:
  vmImage: macOS-latest

variables:
  Major: '7'
  Minor: '2'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.1.101'
  inputs:
    version: 3.1.101

- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0 
  displayName: 'Select the Xamarin SDK version 6.12.0'
      
- script: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_12.app;sudo xcode-select --switch /Applications/Xcode_12.app/Contents/Developer
  displayName: 'Updating xcode version'

- bash: |
   # Write your commands here
   
   echo "Build Script started.."
   
   echo 'Updating fastlane...'
   sudo gem install fastlane
   
   echo $Major
   echo $Minor
   echo $BUILD_BUILDNUMBER
   
   VERSION=$Major.$Minor.$BUILD_BUILDID
   echo $VERSION

   INFO_PLIST_FILE=$BUILD_REPOSITORY_LOCALPATH/Src/MoneyFox.Ios/Info.plist
   echo $INFO_PLIST_FILE
   
   echo "Updating version name to $VERSION_NAME in Info.plist"
   plutil -replace CFBundleShortVersionString -string $BUILD_BUILDNUMBER $INFO_PLIST_FILE
   plutil -replace CFBundleVersion -string $VERSION $INFO_PLIST_FILE
  displayName: 'Set App Version'
  env:
    Major: $(Major)
    Minor: $(Minor)

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'Apple Distribution MoneyFox 2020.p12'
    certPwd: '$(P12password)'
    keychain: temp

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: 'MoneyFox_Distribution_2020.mobileprovision'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'
  inputs:
    versionSpec: 5.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/MoneyFox.sln'

- task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
  displayName: 'Replace tokens in Src/MoneyFox'
  inputs:
    sourcePath: Src/MoneyFox
    filePattern: App.config

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: |
      **/*.Tests.csproj
      !**/MoneyFox.Tests.csproj
  enabled: false

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS '
  inputs:
    solutionFile: Src/MoneyFox.Ios/MoneyFox.iOS.csproj
    configuration: $(BuildConfiguration)
    signingIdentity: $(APPLE_CERTIFICATE_SIGNING_IDENTITY)
    signingProvisioningProfileID: $(APPLE_PROV_PROFILE_UUID)

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/changelog.txt'
    TargetFolder: '$(build.artifactstagingdirectory)/.fastlane'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
